<?php

namespace CMS\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SettingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResourceRepository extends EntityRepository
{
    public function findAllSql()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT r FROM CMSAdminBundle:Resource r ORDER BY r.id DESC'
            );
    }

    public function findByKeywordSql($keyword = '')
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT r FROM CMSAdminBundle:Resource r  WHERE r.name LIKE :keyword ORDER BY r.id DESC"
            )->setParameter('keyword', '%'.$keyword.'%');
    }
}
