<?php

namespace CMS\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SettingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SettingRepository extends EntityRepository
{
    public function findViewBestSql()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT s FROM CMSAdminBundle:Setting s ORDER BY s.id DESC'
            )
            ->setMaxResults(1);
    }
}
